// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/blockchain-explorers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/blockchain-explorers.get').default>>>>
    }
    '/api/rpc-proxy': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rpc-proxy').default>>>>
    }
    '/api/rpc-servers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/rpc-servers.get').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/docus@https+++pkg.pr.new+docus@1304_b79fef1be70f1ab244195d66774a0d68/node_modules/docus/server/routes/sitemap.xml').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.3.1_better-sqlite3@12.6.2_db0@0.3.4_better-sqlite3@12.6.2__ioredis_b6ab51e5dba87f331145231b301cc5f0/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0.5.2_vite@7.3.1_@types+node@24.9.2_jiti@2.6.1_less@4.4.2_lig_ccebd15858fadc852491ff7ad9d8ea80/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/raw/**:slug.md': {
      'GET': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_bufferutil@4.0.9_magicast@0.5.2_utf-8-valida_9fb1a01edc2b18f083422cb9683dc43a/node_modules/@nuxt/content/dist/features/llms/runtime/server/routes/raw/[...slug].md.get').default>>>>
    }
    '/mcp': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+mcp-toolkit@0.7.0_@cfworker+json-schema@4.1.1_agents@0.7.5_@cloudflare+workers-_355c10e38512178b6cedf667dc660192/node_modules/@nuxtjs/mcp-toolkit/dist/runtime/server/mcp/handler').default>>>>
    }
    '/mcp/deeplink': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+mcp-toolkit@0.7.0_@cfworker+json-schema@4.1.1_agents@0.7.5_@cloudflare+workers-_355c10e38512178b6cedf667dc660192/node_modules/@nuxtjs/mcp-toolkit/dist/runtime/server/mcp/deeplink').default>>>>
    }
    '/mcp/badge.svg': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+mcp-toolkit@0.7.0_@cfworker+json-schema@4.1.1_agents@0.7.5_@cloudflare+workers-_355c10e38512178b6cedf667dc660192/node_modules/@nuxtjs/mcp-toolkit/dist/runtime/server/mcp/badge-image').default>>>>
    }
    '/__og-image__/font/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.13_@unhead+vue@2.1.12_vue@3.5.22_typescript@5.9.3___magicast@0.5.2_un_ced3702be2babf4cb20a92ccc97b041e/node_modules/nuxt-og-image/dist/runtime/server/routes/font').default>>>>
    }
    '/__og-image__/image/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.13_@unhead+vue@2.1.12_vue@3.5.22_typescript@5.9.3___magicast@0.5.2_un_ced3702be2babf4cb20a92ccc97b041e/node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/__og-image__/static/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-og-image@5.1.13_@unhead+vue@2.1.12_vue@3.5.22_typescript@5.9.3___magicast@0.5.2_un_ced3702be2babf4cb20a92ccc97b041e/node_modules/nuxt-og-image/dist/runtime/server/routes/image').default>>>>
    }
    '/llms.txt': {
      'GET': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-llms@0.2.0_magicast@0.5.2/node_modules/nuxt-llms/dist/runtime/server/routes/llms.txt.get').default>>>>
    }
    '/llms-full.txt': {
      'GET': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-llms@0.2.0_magicast@0.5.2/node_modules/nuxt-llms/dist/runtime/server/routes/llms-full.txt.get').default>>>>
    }
    '/__docus__/assistant': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/docus@https+++pkg.pr.new+docus@1304_b79fef1be70f1ab244195d66774a0d68/node_modules/docus/modules/assistant/runtime/server/api/search').default>>>>
    }
    '/__nuxt_content/docs/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_bufferutil@4.0.9_magicast@0.5.2_utf-8-valida_9fb1a01edc2b18f083422cb9683dc43a/node_modules/@nuxt/content/dist/runtime/presets/cloudflare/database-handler').default>>>>
    }
    '/__nuxt_content/landing/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_bufferutil@4.0.9_magicast@0.5.2_utf-8-valida_9fb1a01edc2b18f083422cb9683dc43a/node_modules/@nuxt/content/dist/runtime/presets/cloudflare/database-handler').default>>>>
    }
    '/__nuxt_content/info/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_bufferutil@4.0.9_magicast@0.5.2_utf-8-valida_9fb1a01edc2b18f083422cb9683dc43a/node_modules/@nuxt/content/dist/runtime/presets/cloudflare/database-handler').default>>>>
    }
    '/__nuxt_content/docs/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_bufferutil@4.0.9_magicast@0.5.2_utf-8-valida_9fb1a01edc2b18f083422cb9683dc43a/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/landing/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_bufferutil@4.0.9_magicast@0.5.2_utf-8-valida_9fb1a01edc2b18f083422cb9683dc43a/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/info/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.6.2_bufferutil@4.0.9_magicast@0.5.2_utf-8-valida_9fb1a01edc2b18f083422cb9683dc43a/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
  }
}
export {}