/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./.vitepress/theme/components/Button.vue')['default']
    Card: typeof import('./.vitepress/theme/components/Card.vue')['default']
    Grid: typeof import('./.vitepress/theme/components/Grid.vue')['default']
    HeaderLogo: typeof import('./.vitepress/theme/components/HeaderLogo.vue')['default']
    IconModal: typeof import('./.vitepress/theme/components/IconModal.vue')['default']
    IconSet: typeof import('./.vitepress/theme/components/IconSet.vue')['default']
    PillSelector: typeof import('./.vitepress/theme/components/PillSelector.vue')['default']
    Tags: typeof import('./.vitepress/theme/components/Tags.vue')['default']
  }
}
