/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./.vitepress/theme/components/Button.vue')['default']
    Callout: typeof import('./.vitepress/theme/components/Callout.vue')['default']
    Card: typeof import('./.vitepress/theme/components/Card.vue')['default']
    DesignKitItem: typeof import('./.vitepress/theme/components/DesignKitItem.vue')['default']
    Doc: typeof import('./.vitepress/theme/components/Doc.vue')['default']
    DocAside: typeof import('./.vitepress/theme/components/DocAside.vue')['default']
    DocAsideItem: typeof import('./.vitepress/theme/components/DocAsideItem.vue')['default']
    DocFooter: typeof import('./.vitepress/theme/components/DocFooter.vue')['default']
    Environment: typeof import('./.vitepress/theme/components/Environment.vue')['default']
    Footer: typeof import('./.vitepress/theme/components/Footer.vue')['default']
    Grid: typeof import('./.vitepress/theme/components/Grid.vue')['default']
    HeaderLogo: typeof import('./.vitepress/theme/components/HeaderLogo.vue')['default']
    Hero: typeof import('./.vitepress/theme/components/Hero.vue')['default']
    IconSet: typeof import('./.vitepress/theme/components/IconSet.vue')['default']
    PillSelector: typeof import('./.vitepress/theme/components/PillSelector.vue')['default']
    Sidebar: typeof import('./.vitepress/theme/components/Sidebar.vue')['default']
    SidebarItem: typeof import('./.vitepress/theme/components/SidebarItem.vue')['default']
    Tags: typeof import('./.vitepress/theme/components/Tags.vue')['default']
  }
}
