[build]
publish = ".vitepress/dist"
command = "pnpm build"

[[redirects]]
from = "/api/rpc"
to = "https://rpc.nimiqwatch.com/"
status = 200
force = true
headers = { X-From = "Netlify" }

[[redirects]]
from = "/api/rpc/*"
to = "https://rpc.nimiqwatch.com/:splat"
status = 200
force = true
headers = { X-From = "Netlify" }
