declare const computed: any
declare const createError: any
declare const defineAppConfig: any
declare const provide: any
declare const inject: any
declare const queryCollection: any
declare const queryCollectionItemSurroundings: any
declare const queryCollectionNavigation: any
declare const queryCollectionSearchSections: any
declare const ref: any
declare const setPageLayout: any
declare const toValue: any
declare const useAppConfig: any
declare const useAsyncData: any
declare const useColorMode: any
declare const useDocusI18n: any
declare const useFetch: any
declare const useHead: any
declare const useI18n: any
declare const useLazyAsyncData: any
declare const useLocalePath: any
declare const useNuxtApp: any
declare const useRequestEvent: any
declare const useRoute: any
declare const useRuntimeConfig: any
declare const useSeoMeta: any
declare const useSiteConfig: any
declare const useState: <T = any>(...args: any[]) => T
declare const useSwitchLocalePath: any
declare const useToast: any
declare const watchEffect: any
