import { log } from 'console';
import { error } from 'console';
<script setup lang="ts">
import { useData } from 'vitepress'

const { page } = useData()

const webClientRepoUrl = 'https://github.com/nimiq/core-rs-albatross/tree/albatross/web-client'
const isWebClientDoc = page.value.filePath.startsWith('build/web-client')

const editThisLink = isWebClientDoc
  ? webClientRepoUrl
  : `${__REPO_URL__}/blob/main/${page.value.filePath}`

const hash = isWebClientDoc ? __ALBATROSS_COMMIT_HASH__ : __REPO_LAST_COMMIT_HASH__
const lastUrl = isWebClientDoc ? webClientRepoUrl : __REPO_LAST_COMMIT_URL__

const date = computed(() => new Date(isWebClientDoc ? __ALBATROSS_COMMIT_DATE__ : page.value.lastUpdated || Date.now()))

const builtTime = new Intl.DateTimeFormat(navigator.language, { dateStyle: 'short', timeStyle: 'short' }).format(date.value)
const timeAgo = useTimeAgo(date.value)
</script>

<template>
  <nav grid="~ cols-[auto_auto] rows-2 justify-between" mt-96>
    <a :href="editThisLink" target="_blank" rel="noopener" flex="~ items-center gap-6" un-text-12 op70 group>
      <template v-if="!isWebClientDoc">
        Edit this page on GitHub
      </template>
      <template v-else>
        Edit the documentation on GitHub
      </template>

      <div i-nimiq:arrow-top-right w-8 op70 group-hover="translate-x-2 translate-y--2" duration-100ms />
    </a>

    <div flex="~ items-center gap-6" justify-self-end>
      <p :key="page.filePath" text-12 op-70>
        <template v-if="!isWebClientDoc">
          Updated {{ timeAgo }} on {{ builtTime }} (<a :href="lastUrl" target="_blank" rel="noopener" font-bold>{{ hash }}</a>)
        </template>
        <template v-else>
          Documentation autogenerated {{ timeAgo }} on {{ builtTime }}
        </template>
      </p>
    </div>
  </nav>
</template>
